# Generated by Django 2.2 on 2019-04-16 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
